version: "3.7"

services:
  ##########################################################################
  ######                       TOOL SERVER                           #######
  ##########################################################################
  metafacts-server:
    ports:
      - 8005:8005
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
    command: >
      /bin/sh -c "
      uvicorn app.main:app --reload --host 0.0.0.0 --port 8005;
      "
    env_file:
      - .env
    networks:
      - metafacts

networks:
  metafacts: